/**:
  ros__parameters:
    input_frame: "base_link"
    output_frame: "base_link"
    min_x: -90.0
    max_x: 90.0
    min_y: -90.0
    max_y: 90.0
    min_z: -30.0
    max_z: 90.0
    negative: False
    processing_time_threshold_sec: 0.01
